---
- name: set-facts for variables
  hosts: all
  roles:
    - "set-facts"
  become: true

- name: install common-tools
  hosts: all
  roles:
    - "common-tools"
  become: true

- name: install java8
  hosts: all 
  roles:
    - "java8-setup"
  become: true
  
- name: install jenkins
  hosts: infa-jenkins
  roles:
    - "jenkins-setup"
  become: true

- name: install and configure nexus
  hosts: infra-nexus
  roles:
    - "nexus-setup"
  become: true

- name: install tomcat8
  hosts: tomcat
  roles:
    - "tomcat-setup"
  become: true

